# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977dde31ac6dc92f3993df7bb431b6af0b5dae04a8e963e56121516c5f58ca5d6639e16354e90e9544323bff1d3b09718682776649566a8c9b4f15472782f14f

test:
  secret_key_base: 15f2623b9db8135da315adc9f289c4cdea490512327bdee68b47e7e9cb780970a584c2ab829913d93705f11503be68adec8d0d2ed3d0ac1fa32ba4d9c2296b03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
